services:

  ce-workspace:
    container_name: ce-workspace.fnal.gov
    image: gwmsdeveloper/ce-workspace:latest
    networks:
      - gwms
    hostname: ce-workspace.fnal.gov
    tty: true
    stdin_open: true

  factory-workspace:
    container_name: factory-workspace.fnal.gov
    image: gwmsdeveloper/factory-workspace:latest
    volumes:
      - gwms:/var/lib/gwms-factory/.condor/tokens.d
      - ${GMWS_PATH}:/opt/GlideinWMS/glideinwms
    networks:
      - gwms
    hostname: factory-workspace.fnal.gov
    depends_on:
      - ce-workspace
    tty: true
    stdin_open: true

  frontend-workspace:
    container_name: frontend-workspace.fnal.gov
    image: gwmsdeveloper/frontend-workspace:latest
    volumes:
      - gwms:/var/lib/gwms-frontend/.condor/tokens.d
      - ${GMWS_PATH}:/opt/GlideinWMS/glideinwms
    networks:
      - gwms
    hostname: frontend-workspace.fnal.gov
    depends_on:
      - factory-workspace
    tty: true
    stdin_open: true

volumes:
  gwms:
    driver: local

networks:
  gwms:
    driver: bridge
